"""Inventory Monitoring Agent (Phase SC).

Monitors stock levels against defined thresholds and generates alerts
for low stock, out-of-stock, and overstock conditions.

Data source is a STUB — real inventory data must come from ERP/inventory
system integration (placeholder). The agent operates on in-memory snapshot
for testing/demo purposes.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from packages.contracts.enums import AgentResponseStatus
from packages.contracts.models import AgentResponse, ErrorDetail, TaskRequest

logger = logging.getLogger(__name__)


class InventoryAlertType(StrEnum):
    """Types of inventory alerts."""

    LOW_STOCK = "low_stock"
    OUT_OF_STOCK = "out_of_stock"
    OVERSTOCK = "overstock"
    REORDER_POINT = "reorder_point"


class InventoryStatus(StrEnum):
    """Current inventory status for an item."""

    NORMAL = "normal"
    LOW_STOCK = "low_stock"
    OUT_OF_STOCK = "out_of_stock"
    OVERSTOCK = "overstock"


@dataclass
class InventoryItem:
    """Represents a single inventory item with its current stock level."""

    sku: str
    description: str = ""
    quantity_on_hand: int = 0
    reorder_point: int = 0  # Trigger reorder when stock <= this level
    max_stock_level: int = 0  # Upper threshold for overstock warning
    unit_cost: float = 0.0
    location: str = ""  # Warehouse/bin location

    @property
    def is_low_stock(self) -> bool:
        """Item is low stock if quantity <= reorder_point and > 0."""
        return 0 < self.quantity_on_hand <= self.reorder_point

    @property
    def is_at_reorder_point(self) -> bool:
        """Item is exactly at reorder point."""
        return self.quantity_on_hand == self.reorder_point and self.quantity_on_hand > 0

    @property
    def is_out_of_stock(self) -> bool:
        """Item is out of stock if quantity == 0."""
        return self.quantity_on_hand == 0

    @property
    def is_overstock(self) -> bool:
        """Item is overstock if quantity >= max_stock_level."""
        return self.quantity_on_hand >= self.max_stock_level

    @property
    def status(self) -> InventoryStatus:
        """Current status based on quantity thresholds (priority order)."""
        if self.is_out_of_stock:
            return InventoryStatus.OUT_OF_STOCK
        if self.is_at_reorder_point:
            return InventoryStatus.LOW_STOCK  # treat as low (at threshold)
        if self.is_low_stock:
            return InventoryStatus.LOW_STOCK
        if self.is_overstock:
            return InventoryStatus.OVERSTOCK
        return InventoryStatus.NORMAL

    @property
    def stock_value(self) -> float:
        """Total value of current stock (quantity * unit_cost)."""
        return self.quantity_on_hand * self.unit_cost


@dataclass
class InventoryAlert:
    """An alert generated by the inventory monitoring system."""

    alert_type: InventoryAlertType
    sku: str
    description: str = ""
    current_quantity: int = 0
    threshold: int = 0
    severity: str = "info"  # info | warning | critical
    timestamp: float = 0.0
    message: str = ""


@dataclass
class InventorySnapshot:
    """Complete inventory state at a point in time."""

    items: list[InventoryItem] = field(default_factory=list)
    last_updated: float = 0.0
    total_items: int = 0
    total_value: float = 0.0
    alerts: list[InventoryAlert] = field(default_factory=list)

    def add_item(self, item: InventoryItem) -> None:
        """Add an item to the snapshot."""
        self.items.append(item)
        self.total_items = len(self.items)
        self.total_value += item.stock_value
        self.last_updated = _now_seconds()

    def generate_alerts(self) -> list[InventoryAlert]:
        """Generate alerts for all items based on current thresholds.

        Alert priority (first match wins):
          1. OUT_OF_STOCK (critical) — quantity == 0
          2. REORDER_POINT (info) — quantity == reorder_point
          3. LOW_STOCK (warning) — 0 < quantity < reorder_point
          4. OVERSTOCK (warning) — quantity >= max_stock_level
        """
        alerts: list[InventoryAlert] = []
        for item in self.items:
            alert = _check_item(item)
            if alert:
                alerts.append(alert)
        self.alerts = alerts
        return alerts


def _now_seconds() -> float:
    """Get current time in seconds (seconds since epoch)."""
    return time.time()


def _check_item(item: InventoryItem) -> InventoryAlert | None:
    """Check a single item and generate alert if needed.

    Priority order: OOS > at-reorder-point > low > overstock.
    """
    now = _now_seconds()

    # 1. Out of stock — critical (highest priority)
    if item.is_out_of_stock:
        return InventoryAlert(
            alert_type=InventoryAlertType.OUT_OF_STOCK,
            sku=item.sku,
            description=item.description,
            current_quantity=item.quantity_on_hand,
            threshold=item.reorder_point,
            severity="critical",
            timestamp=now,
            message=(
                f"CRITICAL: SKU {item.sku} ({item.description}) is OUT OF STOCK. "
                f"Current quantity: {item.quantity_on_hand}. "
                f"Reorder point: {item.reorder_point}."
            ),
        )

    # 2. At reorder point — info
    if item.is_at_reorder_point:
        return InventoryAlert(
            alert_type=InventoryAlertType.REORDER_POINT,
            sku=item.sku,
            description=item.description,
            current_quantity=item.quantity_on_hand,
            threshold=item.reorder_point,
            severity="info",
            timestamp=now,
            message=(
                f"INFO: SKU {item.sku} ({item.description}) reached reorder point. "
                f"Current quantity: {item.quantity_on_hand}. "
                f"Reorder point: {item.reorder_point}. "
                f"Consider triggering reorder."
            ),
        )

    # 3. Low stock — warning
    if item.is_low_stock:
        return InventoryAlert(
            alert_type=InventoryAlertType.LOW_STOCK,
            sku=item.sku,
            description=item.description,
            current_quantity=item.quantity_on_hand,
            threshold=item.reorder_point,
            severity="warning",
            timestamp=now,
            message=(
                f"WARNING: SKU {item.sku} ({item.description}) is LOW STOCK. "
                f"Current quantity: {item.quantity_on_hand}. "
                f"Reorder point: {item.reorder_point}."
            ),
        )

    # 4. Overstock — warning
    if item.is_overstock:
        return InventoryAlert(
            alert_type=InventoryAlertType.OVERSTOCK,
            sku=item.sku,
            description=item.description,
            current_quantity=item.quantity_on_hand,
            threshold=item.max_stock_level,
            severity="warning",
            timestamp=now,
            message=(
                f"WARNING: SKU {item.sku} ({item.description}) is OVERSTOCK. "
                f"Current quantity: {item.quantity_on_hand}. "
                f"Max stock level: {item.max_stock_level}."
            ),
        )

    return None


class InventoryMonitor:
    """Agent that monitors inventory levels and generates alerts.

    This agent operates on an in-memory inventory snapshot for testing/demo.
    In production, it would connect to an ERP/inventory system to fetch
    real-time stock data.

    Usage:
        monitor = InventoryMonitor()
        monitor.add_item(InventoryItem(sku="SKU-001", quantity_on_hand=5, ...))
        snapshot = monitor.get_snapshot()
        alerts = snapshot.alerts
    """

    def __init__(self) -> None:
        """Initialize the inventory monitor with empty snapshot."""
        self._snapshot = InventorySnapshot()

    @property
    def snapshot(self) -> InventorySnapshot:
        """Current inventory snapshot."""
        return self._snapshot

    def add_item(self, item: InventoryItem) -> None:
        """Add an inventory item to monitor."""
        self._snapshot.add_item(item)

    def add_items(self, items: list[InventoryItem]) -> None:
        """Add multiple inventory items."""
        for item in items:
            self.add_item(item)

    def get_snapshot(self) -> InventorySnapshot:
        """Get the current inventory snapshot with alerts generated."""
        self._snapshot.generate_alerts()
        return self._snapshot

    def get_alerts(self) -> list[InventoryAlert]:
        """Get all current alerts."""
        self._snapshot.generate_alerts()
        return self._snapshot.alerts

    def get_critical_alerts(self) -> list[InventoryAlert]:
        """Get only critical severity alerts (out of stock)."""
        return [a for a in self.get_alerts() if a.severity == "critical"]

    def get_warning_alerts(self) -> list[InventoryAlert]:
        """Get only warning severity alerts (low stock, overstock)."""
        return [a for a in self.get_alerts() if a.severity == "warning"]

    def clear_alerts(self) -> None:
        """Clear all alerts (reset snapshot)."""
        self._snapshot = InventorySnapshot()

    def get_summary(self) -> dict[str, Any]:
        """Get a summary of inventory status for reporting."""
        self._snapshot.generate_alerts()
        snapshot = self._snapshot

        low_stock_count = sum(
            1 for item in snapshot.items if item.status in (InventoryStatus.LOW_STOCK,)
        )
        out_of_stock_count = sum(
            1 for item in snapshot.items if item.status == InventoryStatus.OUT_OF_STOCK
        )
        overstock_count = sum(
            1 for item in snapshot.items if item.status == InventoryStatus.OVERSTOCK
        )
        normal_count = snapshot.total_items - low_stock_count - out_of_stock_count - overstock_count

        return {
            "total_items": snapshot.total_items,
            "total_value": snapshot.total_value,
            "low_stock_count": low_stock_count,
            "out_of_stock_count": out_of_stock_count,
            "overstock_count": overstock_count,
            "normal_count": normal_count,
            "alert_count": len(snapshot.alerts),
            "critical_alert_count": len(self.get_critical_alerts()),
            "warning_alert_count": len(self.get_warning_alerts()),
        }

    async def handle(self, request: TaskRequest) -> AgentResponse:
        """Process an inventory monitoring task.

        This is the main entry point called by the orchestrator.
        Supports actions: check_inventory, get_alerts, get_summary.

        Args:
            request: The task request containing inventory data or action.

        Returns:
            AgentResponse with inventory status or alerts.
        """
        action = request.action

        if action == "check_inventory":
            items_data = request.payload.get("items", [])
            if items_data:
                for item_data in items_data:
                    item = InventoryItem(
                        sku=item_data.get("sku", ""),
                        description=item_data.get("description", ""),
                        quantity_on_hand=item_data.get("quantity_on_hand", 0),
                        reorder_point=item_data.get("reorder_point", 0),
                        max_stock_level=item_data.get("max_stock_level", 0),
                        unit_cost=item_data.get("unit_cost", 0.0),
                        location=item_data.get("location", ""),
                    )
                    self.add_item(item)

            snapshot = self.get_snapshot()

            return AgentResponse(
                task_id=request.task_id,
                agent="inventory_monitor-v1",
                status=AgentResponseStatus.SUCCESS,
                result={
                    "inventory_summary": self.get_summary(),
                    "snapshot": {
                        "total_items": snapshot.total_items,
                        "total_value": snapshot.total_value,
                        "items": [
                            {
                                "sku": item.sku,
                                "description": item.description,
                                "quantity_on_hand": item.quantity_on_hand,
                                "reorder_point": item.reorder_point,
                                "max_stock_level": item.max_stock_level,
                                "unit_cost": item.unit_cost,
                                "location": item.location,
                                "status": item.status.value,
                                "stock_value": item.stock_value,
                            }
                            for item in snapshot.items
                        ],
                    },
                    "alerts": [
                        {
                            "alert_type": alert.alert_type.value,
                            "sku": alert.sku,
                            "description": alert.description,
                            "current_quantity": alert.current_quantity,
                            "threshold": alert.threshold,
                            "severity": alert.severity,
                            "message": alert.message,
                        }
                        for alert in snapshot.alerts
                    ],
                },
            )

        elif action == "get_alerts":
            alerts = self.get_alerts()
            return AgentResponse(
                task_id=request.task_id,
                agent="inventory_monitor-v1",
                status=AgentResponseStatus.SUCCESS,
                result={
                    "alerts": [
                        {
                            "alert_type": alert.alert_type.value,
                            "sku": alert.sku,
                            "description": alert.description,
                            "current_quantity": alert.current_quantity,
                            "threshold": alert.threshold,
                            "severity": alert.severity,
                            "message": alert.message,
                        }
                        for alert in alerts
                    ],
                    "critical_count": len(self.get_critical_alerts()),
                    "warning_count": len(self.get_warning_alerts()),
                },
            )

        elif action == "get_summary":
            summary = self.get_summary()
            return AgentResponse(
                task_id=request.task_id,
                agent="inventory_monitor-v1",
                status=AgentResponseStatus.SUCCESS,
                result={"inventory_summary": summary},
            )

        else:
            return AgentResponse(
                task_id=request.task_id,
                agent="inventory_monitor-v1",
                status=AgentResponseStatus.REJECTED,
                error=ErrorDetail(
                    code="VALIDATION_ERROR",
                    message=f"Unsupported action: {action!r}",
                ),
            )


# ---------------------------------------------------------------------------
# Agent descriptor for registry
# ---------------------------------------------------------------------------

SUPPLY_CHAIN_INVENTORY_CAPABILITIES = frozenset(
    {"supply_chain.check_inventory", "supply_chain.get_alerts", "supply_chain.get_summary"}
)


def create_inventory_monitor(llm=None, settings=None) -> InventoryMonitor:
    """Create an InventoryMonitor instance (factory for registry).

    Args:
        llm: LLM provider (unused — inventory monitoring is rule-based).
        settings: Application settings (unused — thresholds are per-item).

    Returns:
        InventoryMonitor instance.
    """
    return InventoryMonitor()
