# -*- coding: utf-8 -*-
"""Research agent — multi-agent research workflow with LangGraph.

Provides:
- ResearchAgentBase: base class for research agents
- WebSearchAgent: web search via web_search tool
- ArxivAgent: arxiv paper search
- ResearchGraph: LangGraph workflow for research pipeline
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from langgraph.graph import END, START, StateGraph
from langgraph.checkpoint.memory import InMemorySaver

# Optional Hermes tooling — falls back to None if not available in this environment
try:
    from hermes_tools import web_search, web_extract
except ImportError:  # pragma: no cover - hermes_tools only present in Hermes runtime
    web_search = None  # type: ignore[assignment]
    web_extract = None  # type: ignore[assignment]


# Wrappers (monkeypatchable in tests)
async def _call_web_search(query: str, limit: int = 5) -> dict[str, Any]:
    if web_search is None:
        raise RuntimeError("web_search tool unavailable (hermes_tools not installed)")
    return await web_search(query=query, limit=limit)


async def _call_web_extract(urls: list[str], char_limit: int = 5000) -> dict[str, Any]:
    if web_extract is None:
        raise RuntimeError("web_extract tool unavailable (hermes_tools not installed)")
    return await web_extract(urls=urls[:3], char_limit=char_limit)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Research State
# ---------------------------------------------------------------------------

@dataclass
class ResearchState:
    """State carried through research LangGraph workflow."""
    task_id: UUID
    query: str = ""
    domain: str = "web"  # "web" or "arxiv"
    
    # Search results
    search_results: list[dict[str, Any]] = field(default_factory=list)
    search_error: str | None = None
    
    # Extracted content
    extracted_content: list[dict[str, Any]] = field(default_factory=list)
    extraction_error: str | None = None
    
    # Summary
    summary: str = ""
    summary_error: str | None = None
    
    # Final report
    report: str = ""
    
    # Flow control
    current_step: str = "init"
    error: str | None = None
    step_history: list[dict[str, Any]] = field(default_factory=list)
    terminal: bool = False
    final_result: dict[str, Any] | None = None


def _record_step(state: ResearchState, step: str, status: str) -> None:
    state.step_history.append({
        "step": step,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": status,
    })


# ---------------------------------------------------------------------------
# Base Research Agent
# ---------------------------------------------------------------------------

class ResearchAgentBase:
    """Base class for research agents."""
    
    def __init__(self, domain: str = "web") -> None:
        self.domain = domain
    
    async def search(self, query: str, limit: int = 5) -> list[dict[str, Any]]:
        """Search for information. Override in subclasses."""
        raise NotImplementedError
    
    async def extract(self, results: list[dict[str, Any]], char_limit: int = 5000) -> list[dict[str, Any]]:
        """Extract content from search results. Override in subclasses."""
        raise NotImplementedError
    
    async def summarize(self, extracted: list[dict[str, Any]], query: str) -> str:
        """Generate summary from extracted content."""
        # Default: concatenate key snippets
        parts = []
        for item in extracted:
            title = item.get("title", "untitled")
            content = item.get("content", item.get("summary", ""))
            if content:
                snippet = content[:300]
                parts.append(f"**{title}**: {snippet}")
        return "\n\n".join(parts) if parts else f"No content extracted for query: {query}"
    
    async def generate_report(self, summary: str, query: str, domain: str) -> str:
        """Generate final report."""
        return f"""# Research Report: {query}

**Domain**: {domain}
**Generated**: {datetime.now(timezone.utc).isoformat()}

## Summary

{summary}

---
*Generated by Research Agent ({self.__class__.__name__})*
"""


# ---------------------------------------------------------------------------
# Web Search Agent
# ---------------------------------------------------------------------------

class WebSearchAgent(ResearchAgentBase):
    """Web search research agent using web_search tool."""
    
    def __init__(self) -> None:
        super().__init__(domain="web")
    
    async def search(self, query: str, limit: int = 5) -> list[dict[str, Any]]:
        """Search web for query."""
        result = await _call_web_search(query=query, limit=limit)
        return result.get("data", {}).get("web", [])
    
    async def extract(self, results: list[dict[str, Any]], char_limit: int = 5000) -> list[dict[str, Any]]:
        """Extract content from web results."""
        urls = [r.get("url") for r in results if r.get("url")]
        
        if not urls:
            return [{"title": r.get("title", ""), "content": r.get("description", ""), "url": r.get("url", "")} for r in results]
        
        # Extract top 3 results
        extract_result = await _call_web_extract(urls=urls[:3], char_limit=char_limit)
        results_data = extract_result.get("results", [])
        
        extracted = []
        for r in results_data:
            extracted.append({
                "title": r.get("title", ""),
                "content": r.get("content", ""),
                "url": r.get("url", ""),
                "error": r.get("error"),
            })
        
        return extracted


# ---------------------------------------------------------------------------
# Arxiv Agent
# ---------------------------------------------------------------------------

class ArxivAgent(ResearchAgentBase):
    """Arxiv paper search research agent."""
    
    def __init__(self) -> None:
        super().__init__(domain="arxiv")
    
    async def search(self, query: str, limit: int = 5) -> list[dict[str, Any]]:
        """Search arxiv for papers."""
        try:
            from arxiv import Search, SortCriterion
            
            search = Search(
                query=query,
                max_results=limit,
                sort_by=SortCriterion.Relevance,
            )
            
            results = []
            for paper in search.results():
                results.append({
                    "title": paper.title,
                    "authors": ", ".join(author.name for author in paper.authors),
                    "summary": paper.summary[:2000] if paper.summary else "",
                    "url": paper.pdf_url,
                    "published": paper.published.isoformat() if paper.published else "",
                    "categories": ", ".join(paper.categories),
                })
            
            return results
        except ImportError:
            # Fallback: return empty if arxiv not installed
            logger.warning("arxiv package not installed, returning empty results")
            return []
    
    async def extract(self, results: list[dict[str, Any]], char_limit: int = 5000) -> list[dict[str, Any]]:
        """Extract — arxiv results already have summary."""
        return results


# ---------------------------------------------------------------------------
# Research Nodes (LangGraph)
# ---------------------------------------------------------------------------

async def search_node(state: ResearchState) -> ResearchState:
    """Execute search based on domain."""
    _record_step(state, "search", "started")
    
    try:
        if state.domain == "web":
            agent = WebSearchAgent()
        elif state.domain == "arxiv":
            agent = ArxivAgent()
        else:
            agent = WebSearchAgent()
        
        results = await agent.search(state.query, limit=5)
        state.search_results = results
        state.current_step = "search_done"
        _record_step(state, "search", "success")
    except Exception as e:
        state.search_error = str(e)
        state.error = f"Search failed: {str(e)}"
        state.current_step = "end"
        state.terminal = True
        state.final_result = {"status": "failed", "error": state.error}
        _record_step(state, "search", "failed")
    
    return state


async def extract_node(state: ResearchState) -> ResearchState:
    """Extract content from search results."""
    _record_step(state, "extract", "started")
    
    if state.error or not state.search_results:
        return state
    
    try:
        if state.domain == "web":
            agent = WebSearchAgent()
        elif state.domain == "arxiv":
            agent = ArxivAgent()
        else:
            agent = WebSearchAgent()
        
        extracted = await agent.extract(state.search_results)
        state.extracted_content = extracted
        state.current_step = "extract_done"
        _record_step(state, "extract", "success")
    except Exception as e:
        state.extraction_error = str(e)
        state.error = f"Extraction failed: {str(e)}"
        state.current_step = "end"
        state.terminal = True
        state.final_result = {"status": "failed", "error": state.error}
        _record_step(state, "extract", "failed")
    
    return state


async def summarize_node(state: ResearchState) -> ResearchState:
    """Generate summary from extracted content."""
    _record_step(state, "summarize", "started")
    
    if state.error or not state.extracted_content:
        return state
    
    try:
        if state.domain == "web":
            agent = WebSearchAgent()
        elif state.domain == "arxiv":
            agent = ArxivAgent()
        else:
            agent = WebSearchAgent()
        
        summary = await agent.summarize(state.extracted_content, state.query)
        state.summary = summary
        state.current_step = "summarize_done"
        _record_step(state, "summarize", "success")
    except Exception as e:
        state.summary_error = str(e)
        state.error = f"Summarization failed: {str(e)}"
        state.current_step = "end"
        state.terminal = True
        state.final_result = {"status": "failed", "error": state.error}
        _record_step(state, "summarize", "failed")
    
    return state


async def report_node(state: ResearchState) -> ResearchState:
    """Generate final report."""
    _record_step(state, "report", "started")
    
    if state.error or not state.summary:
        return state
    
    try:
        if state.domain == "web":
            agent = WebSearchAgent()
        elif state.domain == "arxiv":
            agent = ArxivAgent()
        else:
            agent = WebSearchAgent()
        
        report = await agent.generate_report(state.summary, state.query, state.domain)
        state.report = report
        state.current_step = "report_done"
        state.terminal = True
        
        state.final_result = {
            "status": "success",
            "query": state.query,
            "domain": state.domain,
            "summary": state.summary,
            "report": state.report,
            "search_results_count": len(state.search_results),
            "extracted_count": len(state.extracted_content),
        }
        _record_step(state, "report", "success")
    except Exception as e:
        state.error = f"Report generation failed: {str(e)}"
        state.current_step = "end"
        state.terminal = True
        state.final_result = {"status": "failed", "error": state.error}
        _record_step(state, "report", "failed")
    
    return state


# ---------------------------------------------------------------------------
# Conditional edges
# ---------------------------------------------------------------------------

def after_search(state: ResearchState) -> str:
    if state.error:
        return "error"
    if state.search_results:
        return "extract"
    return "end"


def after_extract(state: ResearchState) -> str:
    if state.error:
        return "error"
    if state.extracted_content:
        return "summarize"
    return "end"


def after_summarize(state: ResearchState) -> str:
    if state.error:
        return "error"
    if state.summary:
        return "report"
    return "end"


def after_report(state: ResearchState) -> str:
    return "end"


# ---------------------------------------------------------------------------
# Graph builder
# ---------------------------------------------------------------------------

def _build_research_graph() -> Any:
    """Build compiled research workflow graph."""
    graph = StateGraph(ResearchState)
    
    graph.add_node("search", search_node)
    graph.add_node("extract", extract_node)
    graph.add_node("summarize", summarize_node)
    graph.add_node("report", report_node)
    graph.add_node("error", error_node)
    
    graph.add_edge(START, "search")
    graph.add_conditional_edges(
        "search",
        after_search,
        {"extract": "extract", "error": "error", "end": END},
    )
    graph.add_conditional_edges(
        "extract",
        after_extract,
        {"summarize": "summarize", "error": "error", "end": END},
    )
    graph.add_conditional_edges(
        "summarize",
        after_summarize,
        {"report": "report", "error": "error", "end": END},
    )
    graph.add_conditional_edges(
        "report",
        after_report,
        {"end": END},
    )
    graph.add_edge("error", END)
    
    return graph.compile(checkpointer=InMemorySaver())


async def error_node(state: ResearchState) -> ResearchState:
    """Terminal error node."""
    state.terminal = True
    state.final_result = {
        "status": "failed",
        "error": state.error or "unknown error",
        "step": state.current_step,
    }
    return state


# ---------------------------------------------------------------------------
# Research Orchestrator
# ---------------------------------------------------------------------------

class ResearchOrchestrator:
    """Orchestrates research workflow."""
    
    def __init__(self) -> None:
        self._graph = _build_research_graph()
    
    async def execute(
        self,
        task_id: UUID,
        query: str,
        domain: str = "web",
    ) -> dict[str, Any]:
        """Execute research workflow.
        
        Args:
            task_id: Unique task identifier.
            query: Research query string.
            domain: Research domain ("web" or "arxiv").
        
        Returns:
            Final result dict.
        """
        initial_state = ResearchState(
            task_id=task_id,
            query=query,
            domain=domain,
        )
        
        result = await self._graph.ainvoke(initial_state)
        final = result.get("final_result")
        
        if final is not None:
            return final
        return {"status": "failed", "error": "no result"}


# ---------------------------------------------------------------------------
# CLI helper
# ---------------------------------------------------------------------------

async def main() -> None:
    """CLI entry point for research."""
    orch = ResearchOrchestrator()
    
    # Example: web search
    task_id = UUID("00000000-0000-0000-0000-000000000001")
    result = await orch.execute(
        task_id=task_id,
        query="What is LangGraph?",
        domain="web",
    )
    
    print(f"Status: {result.get('status')}")
    print(f"Summary:\n{result.get('summary', '')[:500]}")
    print(f"\nReport:\n{result.get('report', '')[:1000]}")


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
